### ISSUE TITLE
TeachPress 9.0.6 does not work on site with Avada theme

### ISSUE THREAD

**Issue by IlseO76** [winkm89/teachPress#262]
I manage a site with the Avada theme. When updating to TeachPress 9.0.6, the publication list is no longer displayed. You see the [tpcloud] shortcode on the page rather than the publications. I have tested whether it is a conflict with any of the plugins by disabling them all. But that does not solve it. So must be a conflict with the theme. Reverting to 9.0.5 solved it.

**Comment by winkm89** [comment]
I guess Avada is a commercial theme only? Without access to the theme or more information about the underlying error it's impossible to fix it.

Could you activate the [debug options in WordPress](https://developer.wordpress.org/advanced-administration/debug/debug-wordpress/) temporary?  Maybe this helps to find the error.

**Comment by winkm89** [comment]
Hi Ilse, 
Version 9.0.9 should fix the database error.

**Comment by IlseO76** [comment]
Thanks Michael!

**Comment by IlseO76** [comment]
Seems the recent updates have not fixed it... have the same issue now with version 9.0.12. Tried reverting to 9.0.9, did not solve it. Then went back to 9.0.6 and my publication list immediately works again. Which is strange, because I originally had the same problem with updating to 9.0.6 and then I needed to go back to 9.0.5 to solve it... weird. Any thoughts?
